### ISSUE TITLE
obs-ptz will not load with OBS 32

### ISSUE THREAD

**Issue by lloydlavender** [glikely/obs-ptz#281]
obs-ptz will not load with OBS 32

**Comment by AllenVM** [comment]
Yup, also having the same problem with the OBS 32.0.0 update.  Will be rolling back to OBS 31.1.1 until the problem is fixed - happy to test on Mac for you!

**Comment by kq5m9** [comment]
Also issue on 32.0.1

**Comment by kq5m9** [comment]
Same for Windows 10.

**Comment by kq5m9** [comment]
From the OBS Project forum, I noticed the following info in a post regarding the 0.18.1 zip file: (https://obsproject.com/forum/threads/ptz-controls.143676/page-41)

> From Github you get:
> 
> - obs-ptz
>     - bin
>         - 64bit
>             - obs-ptz.dll
>             - obs-ptz.pdb
>             - Qt6SerialPort.dll
>     - data
>         - locale
>             - *.ini files
>  
> but it **MUST** be:
> 
> - data
>     - obs-plugins
>         - obs-ptz
>             - locale
>                 - *.ini files
> - obs-plugins
>     - 64bit
>         - obs-ptz.dll
>         - obs-ptz.pdb
>         - Qt6SerialPort.dll
>  

Upon making those changes, it worked for me. IHTH.

**Comment by sonicSMASH** [comment]
New RC release fixed this, should work

**Comment by glikely** [comment]
> From the OBS Project forum, I noticed the following info in a post regarding the 0.18.1 zip file: (https://obsproject.com/forum/threads/ptz-controls.143676/page-41)
> 
> > From Github you get:
> > 
> > * obs-ptz
> >   
> >   * bin
> >     
> >     * 64bit
> >       
> >       * obs-ptz.dll
> >       * obs-ptz.pdb
> >       * Qt6SerialPort.dll
> >   * data
> >     
> >     * locale
> >       
> >       * *.ini files
> > 
> > but it **MUST** be:
> > 
> > * data
> >   
> >   * obs-plugins
> >     
> >     * obs-ptz
> >       
> >       * locale
> >         
> >         * *.ini files
> > * obs-plugins
> >   
> >   * 64bit
> >     
> >     * obs-ptz.dll
> >     * obs-ptz.pdb
> >     * Qt6SerialPort.dll
> 
> Upon making those changes, it worked for me. IHTH.

The zip layout is correct, It is organized for installing into the new plugin directory under c:\programdata, not the old location in Program Files

**Comment by bigtreetech** [comment]
FYI, still getting the same error after updating to the latest version

<img width="998" height="379" alt="Image" src="https://github.com/user-attachments/assets/5d58eb8c-7133-4263-830d-e473b186549a" />

**Comment by glikely** [comment]
> FYI, still getting the same error after updating to the latest version
> 

Please attach your OBS log file

**Comment by bigtreetech** [comment]
@glikely It seems as if it is not able to find the symbol for the frontend dock.

[2025-10-19 16-58-17.txt](https://github.com/user-attachments/files/22990821/2025-10-19.16-58-17.txt)

**Comment by unlikelystory** [comment]
Same here - OBS 32.0.1 OS X

15:03:48.639: os_dlopen(/Users/selway/Library/Application Support/obs-studio/plugins/obs-ptz.plugin/Contents/MacOS/obs-ptz->/Users/selway/Library/Application Support/obs-studio/plugins/obs-ptz.plugin/Contents/MacOS/obs-ptz): dlopen(/Users/selway/Library/Application Support/obs-studio/plugins/obs-ptz.plugin/Contents/MacOS/obs-ptz, 0x0106): Symbol not found: _obs_frontend_add_dock
15:03:48.639:   Referenced from: <C1AC32F1-91BB-39C6-9633-8D3CA76D47D3> /Users/selway/Library/Application Support/obs-studio/plugins/obs-ptz.plugin/Contents/MacOS/obs-ptz
15:03:48.639:   Expected in:     <6FF1CAFD-E1ED-319F-9B69-FE71F3BD5C2D> /Applications/OBS.app/Contents/Frameworks/obs-frontend-api.dylib
15:03:48.639: 
15:03:48.640: Module '/Users/selway/Library/Application Support/obs-studio/plugins/obs-ptz.plugin/Contents/MacOS/obs-ptz' not loaded

**Comment by glikely** [comment]
Should be fixed in current release

**Comment by spartlow** [comment]
This problem still exists. I'm on Windows with OBS 32.0.2 and just ran the latest (release 54) windows installer. 

The error I see is 
Plugin Load Error
The following OBS plugins failed to load:
obs-ptz
Please update or remove these plugins.

Attaching log but the only relevant line I see is:
12:05:06.552: Module '../../obs-plugins/64bit/obs-ptz.dll' not loaded
though oddly later on:
12:05:06.849: [obs-ptz] plugin loaded successfully (version v0.18.2-rc1)

Full log:
12:05:06.074: CPU Name: Intel(R) Core(TM) i5-6440HQ CPU @ 2.60GHz
12:05:06.074: CPU Speed: 2592MHz
12:05:06.074: Physical Cores: 4, Logical Cores: 4
12:05:06.074: Physical Memory: 15999MB Total, 10429MB Free
12:05:06.074: Windows Version: 10.0 Build 19045 (release: 22H2; revision: 6332; 64-bit)
12:05:06.074: Running as administrator: false
12:05:06.075: Windows 10/11 Gaming Features:
12:05:06.075: 	Game DVR: On
12:05:06.075: 	Game Mode: Probably On (no reg key set)
12:05:06.078: Sec. Software Status:
12:05:06.080: 	Microsoft Defender Antivirus: enabled (AV)
12:05:06.080: 	Windows Firewall: enabled (FW)
12:05:06.082: Current Date/Time: 2025-11-01, 12:05:06
12:05:06.082: Browser Hardware Acceleration: true
12:05:06.082: Hide OBS windows from screen capture: false
12:05:06.082: Qt Version: 6.8.3 (runtime), 6.8.3 (compiled)
12:05:06.082: Portable mode: false
12:05:06.167: OBS 32.0.2 (64-bit, windows)
12:05:06.167: ---------------------------------
12:05:06.245: ---------------------------------
12:05:06.245: audio settings reset:
12:05:06.245: 	samples per sec: 48000
12:05:06.245: 	speakers:        2
12:05:06.245: 	max buffering:   960 milliseconds
12:05:06.245: 	buffering type:  dynamically increasing
12:05:06.249: ---------------------------------
12:05:06.249: Initializing D3D11...
12:05:06.249: Available Video Adapters: 
12:05:06.253: 	Adapter 0: Intel(R) HD Graphics 530
12:05:06.253: 	  Dedicated VRAM: 134217728 (0.1 GiB)
12:05:06.253: 	  Shared VRAM:    8388595712 (7.8 GiB)
12:05:06.253: 	  PCI ID:         8086:191b
12:05:06.253: 	  HAGS Status:    Disabled (Default: No, Driver status: Unsupported)
12:05:06.254: 	  Driver Version: 31.0.101.2111
12:05:06.255: 	  output 0:
12:05:06.255: 	    name=
12:05:06.255: 	    pos={0, 0}
12:05:06.255: 	    size={1920, 1080}
12:05:06.255: 	    attached=true
12:05:06.255: 	    refresh=60
12:05:06.255: 	    bits_per_color=8
12:05:06.255: 	    space=RGB_FULL_G22_NONE_P709
12:05:06.255: 	    primaries=[r=(0.580078, 0.360352), g=(0.334961, 0.559570), b=(0.160156, 0.120117), wp=(0.313477, 0.329102)]
12:05:06.255: 	    relative_gamut_area=[709=0.636064, P3=0.468888, 2020=0.336396]
12:05:06.255: 	    sdr_white_nits=80
12:05:06.255: 	    nit_range=[min=0.500000, max=270.000000, max_full_frame=270.000000]
12:05:06.255: 	    dpi=96 (100%)
12:05:06.255: 	    id=\\?\DISPLAY#LGD0558#4&3a52fc&1&UID265988#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
12:05:06.255: 	    alt_id=\\.\DISPLAY1
12:05:06.256: 	  output 1:
12:05:06.256: 	    name=DELL ST2010
12:05:06.256: 	    pos={0, -900}
12:05:06.256: 	    size={1600, 900}
12:05:06.256: 	    attached=true
12:05:06.256: 	    refresh=59
12:05:06.256: 	    bits_per_color=8
12:05:06.256: 	    space=RGB_FULL_G22_NONE_P709
12:05:06.256: 	    primaries=[r=(0.639648, 0.330078), g=(0.299805, 0.599609), b=(0.150391, 0.059570), wp=(0.313477, 0.329102)]
12:05:06.256: 	    relative_gamut_area=[709=0.998664, P3=0.736186, 2020=0.528164]
12:05:06.256: 	    sdr_white_nits=80
12:05:06.256: 	    nit_range=[min=0.500000, max=270.000000, max_full_frame=270.000000]
12:05:06.256: 	    dpi=96 (100%)
12:05:06.256: 	    id=\\?\DISPLAY#DELF019#4&3a52fc&1&UID198195#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
12:05:06.256: 	    alt_id=\\.\DISPLAY2
12:05:06.256: Loading up D3D11 on adapter Intel(R) HD Graphics 530 (0)
12:05:06.318: D3D11 loaded successfully, feature level used: b000
12:05:06.318: DXGI increase maximum frame latency success
12:05:06.441: ---------------------------------
12:05:06.441: video settings reset:
12:05:06.441: 	base resolution:   1920x1080
12:05:06.441: 	output resolution: 1920x1080
12:05:06.441: 	downscale filter:  Bicubic
12:05:06.441: 	fps:               30/1
12:05:06.441: 	format:            NV12
12:05:06.441: 	YUV mode:          Rec. 709/Partial
12:05:06.442: NV12 texture support enabled
12:05:06.442: P010 texture support not available
12:05:06.442: Audio monitoring device:
12:05:06.442: 	name: Speakers / Headphones (Realtek Audio)
12:05:06.442: 	id: {0.0.0.00000000}.{a8df5997-7bd1-4d42-b23f-b4cc839a2a2d}
12:05:06.449: ---------------------------------
12:05:06.451: No AJA devices found, skipping loading AJA UI plugin
12:05:06.451: Failed to initialize module 'aja-output-ui.dll'
12:05:06.453: No AJA devices found, skipping loading AJA plugin
12:05:06.453: Failed to initialize module 'aja.dll'
12:05:06.453: Skipping module '../../obs-plugins/64bit/chrome_elf.dll', not an OBS plugin
12:05:06.456: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
12:05:06.457: Failed to load 'en-US' text for module: 'decklink-captions.dll'
12:05:06.458: Failed to load 'en-US' text for module: 'decklink-output-ui.dll'
12:05:06.461: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
12:05:06.461: Failed to initialize module 'decklink.dll'
12:05:06.501: [AMF] Unable to load 'amfrt64.dll', error code 126.
12:05:06.503: [AMF] AMF Test failed due to one or more errors.
12:05:06.503: Failed to initialize module 'enc-amf.dll'
12:05:06.513: Skipping module '../../obs-plugins/64bit/libcef.dll', not an OBS plugin
12:05:06.514: Skipping module '../../obs-plugins/64bit/libEGL.dll', not an OBS plugin
12:05:06.514: Skipping module '../../obs-plugins/64bit/libGLESv2.dll', not an OBS plugin
12:05:06.515: [NVIDIA Audio Effects:] NVIDIA denoiser disabled, redistributable not found or could not be loaded.
12:05:06.516: Failed to get NVVideoEffects.dll version info size
12:05:06.516: [NVIDIA VIDEO FX]: FX disabled, redistributable not found or could not be loaded.
12:05:06.542: [obs-browser]: Version 2.26.3
12:05:06.542: [obs-browser]: CEF Version 127.0.6533.120 (runtime), 127.145.7+g2b7d20b+chromium-127.0.6533.120 (compiled)
12:05:06.549: LoadLibrary failed for 'nvEncodeAPI64.dll': The specified module could not be found.
12:05:06.549:  (126)
12:05:06.549: NVENC not supported
12:05:06.549: Failed to initialize module 'obs-nvenc.dll'
12:05:06.552: Module '../../obs-plugins/64bit/obs-ptz.dll' not loaded
12:05:06.810: [obs-websocket] [obs_module_load] you can haz websockets (Version: 5.6.3 | RPC Version: 1)
12:05:06.810: [obs-websocket] [obs_module_load] Qt version (compile-time): 6.8.3 | Qt version (run-time): 6.8.3
12:05:06.810: [obs-websocket] [obs_module_load] Linked ASIO Version: 103200
12:05:06.817: [obs-websocket] [obs_module_load] Module loaded.
12:05:06.819: Skipping module '../../obs-plugins/64bit/Qt6SerialPort.dll', not an OBS plugin
12:05:06.819: Skipping module '../../obs-plugins/64bit/Qt6SerialPortd.dll', not an OBS plugin
12:05:06.825: [vlc-video]: Couldn't find VLC installation, VLC video source disabled
12:05:06.849: [obs-ptz] plugin loaded successfully (version v0.18.2-rc1)
12:05:06.938: ---------------------------------
12:05:06.938:   Loaded Modules:
12:05:06.938:     obs-ptz.dll
12:05:06.938:     win-wasapi.dll
12:05:06.938:     win-dshow.dll
12:05:06.938:     win-capture.dll
12:05:06.938:     vlc-video.dll
12:05:06.938:     text-freetype2.dll
12:05:06.938:     rtmp-services.dll
12:05:06.938:     obs-x264.dll
12:05:06.938:     obs-websocket.dll
12:05:06.938:     obs-webrtc.dll
12:05:06.938:     obs-vst.dll
12:05:06.938:     obs-transitions.dll
12:05:06.938:     obs-text.dll
12:05:06.938:     obs-qsv11.dll
12:05:06.938:     obs-outputs.dll
12:05:06.938:     obs-filters.dll
12:05:06.938:     obs-ffmpeg.dll
12:05:06.938:     obs-browser.dll
12:05:06.938:     nv-filters.dll
12:05:06.938:     image-source.dll
12:05:06.938:     frontend-tools.dll
12:05:06.938:     decklink-output-ui.dll
12:05:06.938:     decklink-captions.dll
12:05:06.938:     coreaudio-encoder.dll
12:05:06.938: ---------------------------------
12:05:06.939: ---------------------------------
12:05:06.939: Available Encoders:
12:05:06.939:   Video Encoders:
12:05:06.939: 	- ffmpeg_svt_av1 (SVT-AV1)
12:05:06.939: 	- ffmpeg_aom_av1 (AOM AV1)
12:05:06.939: 	- obs_qsv11_v2 (QuickSync H.264)
12:05:06.939: 	- obs_qsv11_hevc (QuickSync HEVC)
12:05:06.939: 	- obs_x264 (x264)
12:05:06.939:   Audio Encoders:
12:05:06.939: 	- ffmpeg_aac (FFmpeg AAC)
12:05:06.939: 	- ffmpeg_opus (FFmpeg Opus)
12:05:06.939: 	- ffmpeg_pcm_s16le (FFmpeg PCM (16-bit))
12:05:06.939: 	- ffmpeg_pcm_s24le (FFmpeg PCM (24-bit))
12:05:06.939: 	- ffmpeg_pcm_f32le (FFmpeg PCM (32-bit float))
12:05:06.939: 	- ffmpeg_alac (FFmpeg ALAC (24-bit))
12:05:06.939: 	- ffmpeg_flac (FFmpeg FLAC (16-bit))
12:05:06.939: ==== Startup complete ===============================================
12:05:06.945: Switched to Preview/Program mode
12:05:06.945: ------------------------------------------------
12:05:07.017: All scene data cleared
12:05:07.017: ------------------------------------------------
12:05:07.021: [win-wasapi: 'Desktop Audio'] update settings:
12:05:07.021: 	device id: default
12:05:07.021: 	use device timing: 1
12:05:07.022: [Loaded global audio device]: 'Desktop Audio'
12:05:07.022: [win-wasapi: 'Mic/Aux'] update settings:
12:05:07.022: 	device id: default
12:05:07.022: 	use device timing: 0
12:05:07.022: [Loaded global audio device]: 'Mic/Aux'
12:05:07.025: [win-wasapi: 'Scarlet'] update settings:
12:05:07.025: 	device id: {0.0.1.00000000}.{08ed207e-b703-4ae5-8bc5-44d171dc9e78}
12:05:07.025: 	use device timing: 0
12:05:07.165: WASAPI: Device 'Microphone (Logitech BRIO)' [48000 Hz] initialized (source: Mic/Aux)
12:05:07.182: ---------------------------------
12:05:07.182: [DShow Device: 'Logitech'] settings updated: 
12:05:07.182: 	video device: Logitech BRIO
12:05:07.182: 	video path: \\?\usb#vid_046d&pid_085e&mi_00#6&170bffd3&2&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\global
12:05:07.182: 	resolution: 1920x1080
12:05:07.182: 	flip: 0
12:05:07.182: 	fps: 30.00 (interval: 333333)
12:05:07.182: 	format: MJPEG
12:05:07.182: 	buffering: disabled
12:05:07.182: 	hardware decode: disabled
12:05:07.191: WASAPI: Device 'Microphone (Scarlett Solo USB)' [44100 Hz] initialized (source: Scarlet)
12:05:07.420: WASAPI: Device 'Speakers / Headphones (Realtek Audio)' [48000 Hz] initialized (source: Desktop Audio)
12:05:07.552: warning: deprecated pixel format used, make sure you did set range correctly
12:05:07.812: warning: deprecated pixel format used, make sure you did set range correctly
12:05:07.935: [Media Source 'SMTAV']: settings:
12:05:07.935: 	input:                   rtsp://192.168.100.88/1
12:05:07.935: 	input_format:            
12:05:07.935: 	speed:                   100
12:05:07.935: 	is_looping:              no
12:05:07.935: 	is_linear_alpha:         no
12:05:07.935: 	is_hw_decoding:          no
12:05:07.935: 	is_clear_on_media_end:   yes
12:05:07.935: 	restart_on_activate:     no
12:05:07.935: 	close_when_inactive:     no
12:05:07.935: 	full_decode:             no
12:05:07.935: 	ffmpeg_options:          
12:05:08.002: warning: deprecated pixel format used, make sure you did set range correctly
12:05:08.244: warning: deprecated pixel format used, make sure you did set range correctly
12:05:08.379: [duplicator-monitor-capture: 'Monitor 2'] update settings:
12:05:08.379: 	display: DELL ST2010 (1600x900)
12:05:08.379: 	cursor: true
12:05:08.379: 	method: DXGI
12:05:08.379: 	id: \\?\DISPLAY#DELF019#4&3a52fc&1&UID198195#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
12:05:08.379: 	alt_id: \\.\DISPLAY2
12:05:08.379: 	setting_id: \\?\DISPLAY#DELF019#4&3a52fc&1&UID198195#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
12:05:08.379: 	force SDR: false
12:05:08.382: Switched to scene 'PTZ (SMTAV)'
12:05:08.382: User switched Program to scene 'Sending'
12:05:08.387: ------------------------------------------------
12:05:08.387: Loaded scenes:
12:05:08.387: - scene 'Welcome':
12:05:08.387:     - source: 'Welcome_Img' (image_source)
12:05:08.387:     - source: 'Scarlet' (wasapi_input_capture)
12:05:08.387:         - monitoring: monitor and output
12:05:08.387: - scene 'PTZ (SMTAV)':
12:05:08.387:     - source: 'SMTAV' (ffmpeg_source)
12:05:08.387:         - filter: 'Color Correction' (color_filter_v2)
12:05:08.387:     - source: 'Scarlet' (wasapi_input_capture)
12:05:08.387:         - monitoring: monitor and output
12:05:08.387: - scene 'Wide (logi4k)':
12:05:08.387:     - source: 'Scarlet' (wasapi_input_capture)
12:05:08.387:         - monitoring: monitor and output
12:05:08.387:     - source: 'Logitech' (dshow_input)
12:05:08.387:         - filter: 'Color Correction' (color_filter_v2)
12:05:08.387:         - filter: 'Render Delay' (gpu_delay)
12:05:08.387: - scene 'Sending':
12:05:08.387:     - source: 'Scarlet' (wasapi_input_capture)
12:05:08.387:         - monitoring: monitor and output
12:05:08.387:     - source: 'Sending_Img' (image_source)
12:05:08.387: - scene 'Monitor 2 Send':
12:05:08.387:     - source: 'Scarlet' (wasapi_input_capture)
12:05:08.387:         - monitoring: monitor and output
12:05:08.387:     - source: 'Monitor 2' (monitor_capture)
12:05:08.387: - scene 'Black with audio':
12:05:08.387:     - source: 'Scarlet' (wasapi_input_capture)
12:05:08.387:         - monitoring: monitor and output
12:05:08.387: - scene 'prayers? (NO Audio)':
12:05:08.387:     - source: 'prayers-well-be-back' (text_gdiplus_v2)
12:05:08.387: - scene 'Snow welcome':
12:05:08.387:     - source: 'Scarlet' (wasapi_input_capture)
12:05:08.387:         - monitoring: monitor and output
12:05:08.387:     - source: 'Snow' (image_source)
12:05:08.387:     - source: 'Welcome text' (text_gdiplus_v3)
12:05:08.387: - scene 'Snow sending':
12:05:08.387:     - source: 'Scarlet' (wasapi_input_capture)
12:05:08.387:         - monitoring: monitor and output
12:05:08.387:     - source: 'Snow' (image_source)
12:05:08.387:     - source: 'Sending text' (text_gdiplus_v2)
12:05:08.387: - scene 'Snowy sending':
12:05:08.387:     - source: 'Scarlet' (wasapi_input_capture)
12:05:08.387:         - monitoring: monitor and output
12:05:08.387:     - source: 'Snowy church' (image_source)
12:05:08.387:     - source: 'Sending text' (text_gdiplus_v2)
12:05:08.387: - scene 'Night image with audio':
12:05:08.387:     - source: 'Scarlet' (wasapi_input_capture)
12:05:08.387:         - monitoring: monitor and output
12:05:08.387:     - source: 'Night church' (image_source)
12:05:08.387:     - source: 'Sending text' (text_gdiplus_v2)
12:05:08.387: ------------------------------------------------

**Comment by glikely** [comment]
You have two copies of older versions of the plugin installed. Clear out the plugins from both the c:\program files\obs-studio and c:\programdata\obs-studio locations. Then install the latest version, which is v0.18.2 (not v0.18.2-rc1)

**Comment by spartlow** [comment]
Yes, I deleted the obs-ptz.* files in program files plug-folder and resolved the problem. Ideally, the installer would do that (or instructions would be given to help people migrate), but my installations working now. Thanks.
